### ISSUE TITLE
Bug with the time mark

### ISSUE THREAD

**Issue by Helderjfl** [PaulWoitaschek/MaterialAudiobookPlayer#322]
There seems to be a bug with the time mark, as it pass faster than the audio itself, so that causes a bug, that when I pause the audio and resume it, instead of continuing from 4 second before I paused, it continues from 30s~1m after the time I pause.
The image speaks for itself, the time mark passes the total time of the audio.

![Bug](http://s8.postimg.org/salywg5hh/2015_10_03_05_50_33.png)

I was playing the audio with 1.26 speed.

**Comment by nvx2004** [comment]
This is usually the consequence of the audio file being corrupted. If the file in question is an MP3, you might try to find possible synchronization errors e.g. using mp3splt (Automatic split/Synchronization error mode). Otherwise you could re-encode it into another format (such as OGG/Vorbis) and then see if it helped.

**Comment by PaulWoitaschek** [comment]
Yes, looks like defect audio. What @nvx2004 suggested should work!
