### ISSUE TITLE
Request ability to export/backup bookmarks or database 

### ISSUE THREAD

**Issue by jaedlund** [PaulWoitaschek/MaterialAudiobookPlayer#367]
Thank you for creating this program and having a "bookmark on sleep" function. I now have a large number of bookmarks which I'd like to both backup and access on my computer. Could you please add a way to share or backup the database? I couldn't figure out a way to access the database without rooting the phone, which is, unfortunately impossible at the moment.

Thanks.

**Comment by irregularisnotrandom** [comment]
+1

I got burned by lack of backup when i i had to roll back due yo failed upgrades.

**Comment by deoren** [comment]
+1

**Comment by PaulWoitaschek** [comment]
An import / export functionality would require too much work with little benefit for most of the users.

**Comment by leafcutterant** [comment]
Since #902 makes people transfer to another app release track, this feature would be very beneficial in transferring progress, bookmarks, settings, etc.

**Comment by leafcutterant** [comment]
@PaulWoitaschek is there at least a way to do this by copying/pasting program files?

**Comment by micressor** [comment]
> An import / export functionality would require too much work with little benefit for most of the users.

@PaulWoitaschek I love this plain and simple app.
That's why I really miss the import/export functionality. There are also good examples (e.g. FairEmail, AntennaPod and Privacy Browser).
Maybe this could be adapted with little effort?
Or would a financial donation from those involved in the pull request help? 

Anyway, thanks for this app.
