### ISSUE TITLE
The following file may be corrupt

### ISSUE THREAD

**Issue by yaymeh** [PaulWoitaschek/MaterialAudiobookPlayer#375]
Using 2.4.x, I'm getting the error mesage "Defect file - The following file may be corrupt" - seemingly randomly - with different mp3 files. The file is still playing fine after that, unless seeking is attempted which results in the same error message and the player stopping to work until restart. 

All the tested mp3 files work perfectly with 2.4.3 and were tested with vanilla ffmpeg on another machine ( no errors, structure intact ). 

The logs are... "confusing". FFMPEG seems to be trying way too hard (spamming, really, examining all of the audiobooks no matter which one is playing, the whole time while it's playing over and over again). I'm not familiar enough with android to learn anything from those logs, but these lines kind of look suspicious (not in original order / context):

E/AudioTrack( 6294): Discontinuity detected [expected 10583080784, got 10583287722]
E/MediaMetadataRetrieverJNI( 6294): getEmbeddedPicture: Call to getEmbeddedPicture failed.
D/ExtendedUtils(  374): extended extractor not needed, return default
E/MetadataRetrieverClient(  374): failed to extract an album art
E/MediaMetadataRetrieverJNI( 6294): getEmbeddedPicture: Call to getEmbeddedPicture failed.

The way the logs "feel" while I play with the buttons reminds me a bit of debugging multi-threading problems (thread-safety?) - don't know why, really. Maybe just because it looks so messy and I have no idea what I'm doing :D

**Comment by PaulWoitaschek** [comment]
Please update to the latest version.

**Comment by yaymeh** [comment]
What's the "newest version"? Do you mean compile from development branch? Can't find a release newer than 2.4.4.1

**Comment by PaulWoitaschek** [comment]
Please use 2.4.2.2. That is the last version released. The newer versions are not stable as there are problems with the new media player.

The error you discovered comes from switching to ExoPlayer and manipulating the ByteBuffer by Sonic. Because of that disconuity is detected. That works in most of the cases but in some it does not. That is the reason why I'm maintaining two versions right now.

In case you are able to fix the issue, here is the [Renderer](
https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/develop/audiobook/src/main/kotlin/de/ph1b/audiobook/playback/SpeedRenderer.kt).

The log you posted describe two things

> E/MediaMetadataRetrieverJNI( 6294): getEmbeddedPicture: Call to getEmbeddedPicture failed.
> E/MetadataRetrieverClient( 374): failed to extract an album art
> E/MediaMetadataRetrieverJNI( 6294): getEmbeddedPicture: Call to getEmbeddedPicture failed.

These are related to finding covers from audio files. This is not related to playback at all.

> E/AudioTrack( 6294): Discontinuity detected [expected 10583080784, got 10583287722]
> D/ExtendedUtils( 374): extended extractor not needed, return default

These are messages about the actual playback.

I am like 100% sure that the issue has nothing to do with threading. It is 
* either a bug in ExoPlayer
* a bug on your phone so ExoPlayer receives false values
* A problem in the renderer

It is most probably no 3.

**Comment by yaymeh** [comment]
Ok thanks, now I get it!

Does that mean the bleeding edge / 2.4.4+ versions don't need testing + no bug reports for those should be submitted at the moment / until it's less "volatile"?

**Comment by PaulWoitaschek** [comment]
The new version should be at a point now where it seems quite stable.

So it needs testing, yes. The issue you mention should be fixed by switching to VLC.

If you like you can participate in the [Beta](https://play.google.com/apps/testing/de.ph1b.audiobook), that would be really great.
