### ISSUE TITLE
Player not hiding subfolder media

### ISSUE THREAD

**Issue by arpaulnet** [PaulWoitaschek/MaterialAudiobookPlayer#390]
If you add a "folder with multiple audiobooks", only the top directory has a `.nomedia` file created.  I'm not sure if this is a bug with music players or not, but most of them are not treating `.nomedia` recursively.

To give more specifics:
* My main dir is `/sdcard/Audiobooks`
* There is a `/sdcard/Aduiobooks/.nomedia` generated when you tick the option to hide from music players
* There is not a `/sdcard/Audiobooks/ExampleBook/.nomedia` generated
* This hides any music files in `/sdcard/Audiobooks/`, but not audio files in child folders.

My current workaround is to manually create a `.nomedia` file in each of my child directories.  If it makes any difference, I'm currently using CM 12.1.  I've tested this with the built-in music player, as well as a few of the more popular apps found on Google Play.

**Comment by PaulWoitaschek** [comment]
I was digging in the source code and the definition of what is treated as no media can be found [here](https://android.googlesource.com/platform/frameworks/base/+/cd92588/media/java/android/media/MediaScanner.java#1403).
Therefore when a parent file which has a `.nomedia` file in it the whole dir is detected as not scannable for the `MediaScanner`. So I'll stick to that and expect from Media Players to respect that rather than creating multiple files.
