### ISSUE TITLE
Unable to attach new cover 

### ISSUE THREAD

**Issue by Josieb1** [PaulWoitaschek/MaterialAudiobookPlayer#412]
I have just download the new version 2.6.0.1 and have tried to use the cover picker. The cover was located via the picker but I cannot see how to actually attach the cover to the audio book? 

The options on the cover picker appear to be only 

View original image
Search by image
Send feedback
Plus the X to close out and the home and refresh buttons

**Comment by PaulWoitaschek** [comment]
When you click on a cover you see in the cover picker, a dialog pops up. When you press set in that dialog the cover should be chosen.
Or am I missing something?

**Comment by Josieb1** [comment]
Hi Paul

I'm not getting a dialog pop up when selecting a cover. How should the dialog pop up be shown? Pressing the cover doesn't generate any pop up. I'm using an Asus Memo Pad 7. 

I select Edit Cover from the three dots. That goes to a Google session showing covers. I select one and it shows in the middle of the Google screen. That's it. No pop up appears, and I only have the X for go back or the three dots which shows View, Search and Feedback. 

Regards 

Joanne

**Comment by andrewjmetzger** [comment]
Hi. Wanted to chime in and confirm the bug on my Galaxy S5, Android 5.0. 

Following the same steps as above, I cannot attach any covers either.

**Comment by Darkmatter81** [comment]
Me neither, when I click Edit Cover I'm taken to a Google image search and from there I don't see any option to attach the chosen image

**Comment by PaulWoitaschek** [comment]
Once you click on a cover it should be directly selected.

Can you please follow [these instructions](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/wiki) and send me the log?

**Comment by Josieb1** [comment]
Paul 

I can't do much without a debug build to install. Can you supply a link where I can download one please. 

Thanks 

Joanne

**Comment by PaulWoitaschek** [comment]
I totally forgot the version :D

[110-2016-02-07-nightly1-audiobook-debug.apk.zip](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/files/134317/110-2016-02-07-nightly1-audiobook-debug.apk.zip)

**Comment by Josieb1** [comment]
Hi Paul 

I've installed the app and sent the log, it's coming from a different email address and this one is not installed on my android tablet. 

Regards

**Comment by Darkmatter81** [comment]
I've also just submitted some logs too Paul from ossboy email address. Hopefully with both out logs the

**Comment by PaulWoitaschek** [comment]
Thank you two.

I don't know how to solve this. Your logs show sth like this:

```
13:42:27	I/[ImagePickerFragment$onViewCreated]	page started with https://www.google.co.uk/search?safe=on&site=imghp&tbm=isch&q=Antifragile:+Things+That+Gain+from+Disorder+cover&gws_rd=cr&ei=wnjEVsmHIYq1UciyhcgF

13:42:27	I/[ImagePickerFragment$onViewCreated]	img url https://www.google.co.uk/search?safe=on&site=imghp&tbm=isch&q=Antifragile:+Things+That+Gain+from+Disorder+cover&gws_rd=cr&ei=wnjEVsmHIYq1UciyhcgF did not contain the imgurl parameter.
```

And
```
13:38:05	I/[ImagePickerFragment$onViewCreated]	page started with https://www.google.co.uk/search?safe=on&site=imghp&tbm=isch&q=Necropolis_+Whyborne+%26+Griffin+(Unabridged)+cover&gws_rd=cr&ei=vXfEVs72KIidUYaKj8AO

13:38:05	I/[ImagePickerFragment$onViewCreated]	img url https://www.google.co.uk/search?safe=on&site=imghp&tbm=isch&q=Necropolis_+Whyborne+%26+Griffin+(Unabridged)+cover&gws_rd=cr&ei=vXfEVs72KIidUYaKj8AO did not contain the imgurl parameter.
```

So somehow you are getting a different response format than I do.
Can you check this version? I have set a regular browser as the user agent.
[110-2016-02-07-nightly1-audiobook-debug.apk.zip](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/files/134584/110-2016-02-07-nightly1-audiobook-debug.apk.zip)

**Comment by Darkmatter81** [comment]
OK Paul, I've just sent you new logs using the updated debug Material Player. Good luck. All I see still is the Google images Web page but there is nothing to do. 

I wonder if perhaps me and Joanne are running specific apps that may prevent this feature. I have a rooted device, with custom ROM with ad blocking. My system is Android Marshmallow 6.0.1

**Comment by rafaeln** [comment]
I am actually experiencing the same issue. Running unrooted 5.0.1

**Comment by Josieb1** [comment]
I'm out now so can't do anything until later now but my Asus is unrooted. It has hardly any apps on it and is running android 5.0. 

Joanne

**Comment by Josieb1** [comment]
The second DB Material Player won't install on my ASUS so I'm unable to provide any logs from that one. 

Joanne

**Comment by mdvanes** [comment]
I would just like to inform you that this also occurs on my HTC One M7, with Android 5.0.2. This is with the most recent production version of the app from the Play Store.

**Comment by PaulWoitaschek** [comment]
I think this is more of a country issue. Where do you live? All UK?

**Comment by mdvanes** [comment]
The Netherlands in my case.

**Comment by PaulWoitaschek** [comment]
We need a developer here to find out what to do.

**Comment by Josieb1** [comment]
I'm in the UK. I'm not a developer. 

Joanne

**Comment by Darkmatter81** [comment]
I'm in the UK too. What makes you think this is a country issue?

**Comment by Josieb1** [comment]
Paul

The logs we both sent yesterday show the words 'did not contain the imgurl parameter.' Is that the dialog pop up none of us are seeing? 

If you are seeing the dialog pop up and no one else is it must be something to do with your device or how you are doing your testing as it appears no one but you is getting the cover selected. I'm not sure how that helps you but it seems clear to me that it's not android version or country specific. 

Joanne

**Comment by Darkmatter81** [comment]
Paul,  if it is country specific, maybe you could install an app called Hola. It creates a VPN that can allow selected apps to run as if in a target country. Perhaps that may be of help testing?

**Comment by Darkmatter81** [comment]
Paul, I'm a former developer, currently learning a little Android development, but not much experience. I can possibly help but must say over the next few days my time is a little limited because of work duties etc. 

I don't have github account, will I still be able to clone the Material Player project? Any necessary permissions I need? 

I'm using Android Studio to learn development. Is your profile Android studio friendly?

**Comment by rafaeln** [comment]
I have this issue in spite of being in the US

Typed on a tiny screen

**Comment by webmanoffesto** [comment]
I'm using a Galaxy S4 (in the USA) and I can't get to the Cover Picker either.

**Comment by andrewjmetzger** [comment]
Hello, all.  Sorry for the late reply!  After examining the related logs above (and my own), I have found that the bug is not region-specific.  Though I hope for an expedient resolution, here's a workaround in the interim:

## Workaround
### Notes

- Before following these directions, remove the affected books from the app's library to ensure success.  To do so, tap *Preferences**, then **Audiobook folder**.  Tap the **deletion icon** for the affected book, and tap **remove** when asked to confirm.
- it is highly recommended that the books stored are organised as follows: On the device or SD card, create a generic folder, e.g., **Audiobooks**. Inside this folder, create a folder named after the book title. Store the book's files within that subfolder. Do this for each book.
- You will need:
    -  an app capable of moving and renaming files, such as **ES File Explorer** (free). ([Download here](https://play.google.com/store/apps/details?id=com.estrongs.android.pop))
    - Internet access. (Alternatively, a pre-selected image file stored on device.)

#### Steps
_If the image to be used is already downloaded, skip to step number five (5) below._
1. Open **Google Chrome** on your device.
2. Perform an image **search for a book cover**.
3. To bring up the image details, **tap a result thumbnail**.
4. Next, save the file. In Chrome, **long-press** (tap and hold) to display the context menu. From the menu, select **Save image**.
5. **Move the downloaded image into the same folder as the book files. (Tip: If using ES File Explorer,  follow the [general instructions here](http://www.estrongs.com/eshelp/en/local.htm).)
6. Once the image is in the target folder, **rename the image** to `cover`, keeping the original extension.
7. Add the book to Material Player. From the **Preferences** screen, select **Audiobook folder**. Next, **tap the + button**.  At this point, if following the note on organisation above, choose **Folder with multiple books** and then **select the main audiobooks folder**. Otherwise, **select single book**.
8. Finally, **press back two times** to return to the main screen, where books and covers should appear.
____

I hope this helps everyone affected!
Andrew

**Comment by webmanoffesto** [comment]
Wow, that's too bad. I liked adding the covers in Material Player by clicking on the (missing) book cover and browsing the cover images until I found one that fit and that I liked. Why is that ability gone now?

**Comment by andrewjmetzger** [comment]
@webmanoffesto I am not a developer for android, so feel free to take this with a grain of salt. However, I believe it has to do with the way native webview is implemented, not allowing the context menu to display. In other applications, developers specify which menu options should appear (such as only the **save image** option.), or alternatively, using intents.

**Comment by PaulWoitaschek** [comment]
> Wow, that's too bad. I liked adding the covers in Material Player by clicking on the (missing) book cover and browsing the cover images until I found one that fit and that I liked. Why is that ability gone now?
Because google turned its image API off.

Solution will be provided in the next release and is already in dev branch..

**Comment by Josieb1** [comment]
Thank you Paul. I’ve just changed Android devices which is why I couldn’t test anything out earlier. Looking forward to the update. 

Joanne

**Comment by Darkmatter81** [comment]
Look forward to the update Paul. Thanks for the good work!

**Comment by webmanoffesto** [comment]
"Solution will be provided in the next release and is already in dev branch.."
Great, I'm looking forward to it.

**Comment by webmanoffesto** [comment]
The cover images often end up stretched out horizontally or cut off. What is the best image size for the cover.jpg file? Can I add a cover.png file instead?

**Comment by webmanoffesto** [comment]
I checked the dimensions of an image which seemed to display correctly in MaterialAudiobookPlayer
and it was 1200W x 1079H.
