### ISSUE TITLE
Stop after file/chapter

### ISSUE THREAD

**Issue by jtuc** [PaulWoitaschek/MaterialAudiobookPlayer#426]
Add a button/option to stop playback after finishing the current file (or chapter, after chapter support is added.)

**Comment by PaulWoitaschek** [comment]
I want to keep it as simple as it is.

**Comment by smartass101** [comment]
This is a major feature I really miss. In many cases it is preferable to using a sleep timer, because the sleep timer cannot be set with seconds resolution. Therefore, often I want to finish a chapter before I fall asleep and if the timer cuts off just by a half a minute too soon, then I have to turn over and fiddle with my phone and set a new timer (which will likely overflow a bit). Perhaps a compromise would be to add seconds resolution to the timer and ideally also a button which would set the currently remaining time on chapter/file as the timer value.
