### ISSUE TITLE
Audio position resets when stopping, file lenght shown too short

### ISSUE THREAD

**Issue by Spreadcat** [PaulWoitaschek/MaterialAudiobookPlayer#443]
Hi,

I have got an audio file that does not show me any errors in the metadata, but the time length and current position is not releated to the actual playing time. When stopping the playback and taking it up again, the position resets to the length  (~5min) displayed and goes playing on from there on.

MP Version 2.7.2.1
Android: 5.1

**Comment by kaelsidhe** [comment]
I too am having this problem with multiple Audiobooks.  I have a theory on how this may be happening.

I don't like Audiobooks with a bunch of tiny files to manage.  The first thing I do when I get an audiobook like that is to join all the mp3 files up into one big file.  This is far easier to manage but it seems that Material Player may be getting Audiobook duration from someplace other than the physical statistics of the file.

This is extremely problematic when the player loses my place because it won't let me skip forward beyond the point where it thinks the book ends!  So I have an 8 hour Audiobook but Material Player says it's 40 minutes.  Around the 3 hour mark it lost its place and reset back a chapter that was prior to the 40 minute mark.  It won't let me fast forward or skip beyond 40 minutes so my only option is to give up on this book or listen to the first 3 hours all over again and hope it doesn't lose it's place again.

So I'd love to see this fixed but as a workaround it would be nice if you could tell me where Material Player is getting its file statistics so that maybe I can find a utility to reset that statistic correctly.  Thanks!

**Comment by kaelsidhe** [comment]
Update: I figured out what the problem is.  Material Player only supports files with a fixed bit rate.  If the Audiobook is variable bit rate then it incorrectly computes the length and causes issues.  I converted the file to a fixed bit rate it works fine in the player now.

**Comment by PaulWoitaschek** [comment]
No, Material Player also does support filex with VBR. You can't just concat files, you have to adjust the headers. This can be done with a program like [VBRFix](http://home.gna.org/vbrfix)

**Comment by Spreadcat** [comment]
Thanks for following up on this and providing a solution ;) Merry Christmas!

**Comment by white-gecko** [comment]
The VBRFix link by @PaulWoitaschek does not work, but for debian it is here: https://packages.debian.org/src:vbrfix https://tracker.debian.org/pkg/vbrfix
But in my case it says `File Is Not VBR No need to do anything to it`.

Maybe the best option is:

    ffmpeg -i infile.mp3 -acodec libopus  outfile.ogg

this is saves more then half the size in my case and as I've heard (https://en.wikipedia.org/wiki/Opus_(audio_format)) the opus format is quite good.
