### ISSUE TITLE
Suggestion: Ability to mark/tag an audio book as "read"

### ISSUE THREAD

**Issue by kentfredric** [PaulWoitaschek/MaterialAudiobookPlayer#453]
I have this feeling I want to have some sort of "reading list", or at least, a way to keep track of what I've read in a way other than just mentally tracking it ( because I'm forgetful ).

The simplest thing that could work here is an ability to somehow hide or mark "Completed" a given audiobook, so that it no longer shows up in the main listing.

I guess you could possibly track this metadata automagically without need for any specific user interface, but implementing manual categorization seems simpler. 

Under Automagical, you could break books down into three categories:
- Books that haven't been read/listened to at all ( "unread" )
- Books that have been listened to partially ( "in progress" )
- Books that have been played to completion ( "read" ).

Either way, even without this feature, its a great app :)

**Comment by doughsay** [comment]
I'd like to second this.  I currently use "Smart Audiobook Player", which is pretty good, but was looking around for alternatives and found this.  One thing that my current app does that I would miss switching to this is categorization.  It implements the ones you suggest: unread, in progress, and read.  I suggested to the developer to add "abandoned" as well, because I start many books and lose interest in them if they're not that great... but the suggestion was never acted upon... :(

**Comment by PaulWoitaschek** [comment]
I like to keep it simple. The design of MAP is rather to have only a few books and delete them when you are done.
We don't provide any kind of sorting or selection so having a larger collection does not make sense.
