### ISSUE TITLE
Issue in locating stored audio books

### ISSUE THREAD

**Issue by DC9413** [PaulWoitaschek/MaterialAudiobookPlayer#475]
Have a file on SD card containing all my audio books. Program only finds a fraction of them. I have 6 books from 1 author.  All files are listed starting with we authors name-book title-year. Of the 6 only one shows up.  RunnING on android 6.x.. thanks.  Love the player...

**Comment by sandybeachit** [comment]
Unfortunately i get the same issue.

I am running:

Samsung Note 3 (HLTE - International) / Temasek CM13 (Android 6.0.1) Rooted

I have tried reverting to a stock rom and having the audiobooks on internal memory and on two different micro sd cards.

Ok so my current folder structure is:

SD Card > Audtiobooks > Author > Book Series Name > Each book in their own folder

So for the Newsflesh Trilogy (http://www.miragrant.com/series/newsflesh/) i have it as:

SD Card > Audtiobooks > Mira Grant > Newsflesh > 01 - Feed
SD Card > Audtiobooks > Mira Grant > Newsflesh > 02 - Deadline
SD Card > Audtiobooks > Mira Grant > Newsflesh > 03 - Blackout
SD Card > Audtiobooks > Mira Grant > Newsflesh > 04 - Rise

The problem i am getting is that Materiel Audiobook Player only displays the first book and no other books in the series, but if i move all four books to "SD Card > Audtiobooks" then all four books appear and play and work fine.

I get the same issue with books from other authors such as HG Wells, Author Conan Doyle, Harry Potter etc, so if you have the audiobooks each in their own folder in the audiobooks folder all the books appear fine, but if they are in the above structure i use then your only see the first book in the folder.

I have a friend who has a Samsung Note 5 (HLTE - International) (Stock not rooted) and the same issue as above happens, exactly the same.

Are there log files i can send on debugging i can turn on to capture how the app works so you can see what is going on ?

I am happy to do further testing if you advise what tests to do.

But right now i have just moved all my audiobooks into my main audiobook folder so i can use your app but i fear other users who are new to your app may simply not use it due to this bug.

Fantastic app though ! Exactly what i was after !!

Thanks

David

**Comment by sandybeachit** [comment]
From what i can tell i am getting the same problem as DC9413, seems the bug might be only for people running Android 6.

Does anyone else have this issue if they are running Android 5 or below ?

**Comment by sandybeachit** [comment]
same as issue #460

**Comment by OdinVon** [comment]
Note 4
Android 6.0.1
Material player lost the SD card.
When I try to point it back to the SD card, it says it switched, but does not update the folder list (still shows the internal memory list) and cannot locate any audio books.

**Comment by PaulWoitaschek** [comment]
Directly related to #500
