### ISSUE TITLE
Playback speed is missing

### ISSUE THREAD

**Issue by trentmduty** [PaulWoitaschek/MaterialAudiobookPlayer#507]
Hello!
The playback speed feature is missing after last update.
How it can be fixed?
Thank you!

**Comment by 11davelove** [comment]
Yes, please help. Mine is gone too. I love the app though!

**Comment by PaulWoitaschek** [comment]
Sorry for that. The custom speed was very instable and led to many crashes.

As of now the custom speed is only available on Marshmallow and greater.

Anyways the developers of exoplayer scheduled custom speed for all apis in Q4 this year, so it might come soon.
See [this thread](https://github.com/google/ExoPlayer/issues/26#issuecomment-253196444)

**Comment by bitinerant** [comment]
I understand your reasoning--stability is important.  However, rather than removing the feature, wouldn't it be better to add a warning when the user changes the playback speed on older phones?  I cannot upgrade to Marshmallow and listen to most podcasts at 1.7X or higher, so this means I will be building my own MaterialPlayer or searching for another one unless the feature is promptly restored.
