### ISSUE TITLE
Won't play new books

### ISSUE THREAD

**Issue by tautrimas** [PaulWoitaschek/MaterialAudiobookPlayer#521]
Hey,

Awesome software here, but there are tons of 1 star comments and I experienced this myself recently. Since mid or end of November, new books cannot be played or seeked. After a while of waiting, the player just crashes. Absolutely unusable software in this state.

Although, it can play my old books just fine. My new books are MP3 with 22K sampling rate. Nothing out of ordinary, all other players on Android can play those files.

**Comment by MaximilianKindshofer** [comment]
Ok so I am not the only one? I tried to convert the audiobooks via ffmpeg to all kinds of formats but nothing works. On an alternative audiobook player the same files work.

**Comment by MaximilianKindshofer** [comment]
Possible Workaround: Reinstall Material player.

Could be a permissions problem?

**Comment by PaulWoitaschek** [comment]
I'm aware of this issue but I don't have the time to investigate.

**Comment by tautrimas** [comment]
Wow, reinstalling helped, though, positions have been lost. Good that I didn't have many books so no biggie.

**Comment by Musiphilos** [comment]
I realized that this app does not have the possibility of exporting the settings, including the bookmarks.
This means that if we have a bug like this one, or need to reset the OS, or need to change phones, a lot of useful information will be lost.

Does anyone know a way to save my bookmarks and import back when I reinstall the app?

Thank you

**Comment by PaulWoitaschek** [comment]
Done. Fixed as of [2.9.1.2](https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/releases/tag/v2.9.1.2).

The problem arised due to removing an unsed column which had a `NOT NULL` constraint and SQLite failing silently upon insert. This affected all users who upgraded from a version <= `2.8.0.2`.
The solution is to recreate the table and popuplate it with the old data.

As of `2.9.1.1` I do a `throwOnInsert` so there won't be any more silent failures in the future.
Sorry for the inconvenience and the time it took to fix this - I'm quite busy. I will adress fatal issues with a higher priority in the future.
