### ISSUE TITLE
freeze when pressing play

### ISSUE THREAD

**Issue by taiko000** [PaulWoitaschek/MaterialAudiobookPlayer#558]
From time to time, the app freezes when pressing the play button. I'm just using a single audiobook and usually just use start/stop button.
Swiping away the the app (probably only destroys the activity) and restarting the app does not fix the problem, because it freezes again when play is pressed. 
Removing the audio-book and re-adding the same one in the setting also does not solve the problem. 
Only force-killing the app process helps. 

Audiobook format: mp3, small ~30 mb parts
Device: Nexus 4, 5.1.1 stock rom
Output device: bluetooth headset

**Comment by MrReSc** [comment]
I had simular problem. I tried quite a lot: Reinstalling the app, clean chache, installed diffrent version...
Finally I deleted my whole podcast folder and copied all podcast newly to my phone. SInce then, I never had a crash of MaterialPlayer. There was an second .nomedia file in a subfolder. Maybe this had triggered the crash.

**Comment by PaulWoitaschek** [comment]
If this is still happening with the latest versions, please comment and I'll re open
