### ISSUE TITLE
Playback Service is always running, even when app is not in use

### ISSUE THREAD

**Issue by Cormak** [PaulWoitaschek/MaterialAudiobookPlayer#602]
For some reason,  the playback service is always running in the background, even when the app isn't running onscreen or has the notification up. It just keeps running in the background until you turn off your phone or force close it. 

Can we please only have the app running in the background when its onscreen or has the notification up? There's no need for this app to have a running process even when we are not using it. It should completely shut itself down when not being used at all. 

App-Version: 3.3.5
Phone Name: Moto X Pure Edition
Android Version: Android 7.1.2

**Comment by juvenalaraujo** [comment]
This is also happening to me and I totally agree with you. 
Is this made on purpose or is it a bug?

App version 3.4.0, on Android 7.0

**Comment by PaulWoitaschek** [comment]
This is on purpose.
However I changed this behavior with the latest version, so the service will shut itself down after 20 seconds in stopped state.

**Comment by Cormak** [comment]
@PaulWoitaschek Thank you for understanding and changing the behavior of your app. The less unnecessary running processes on our phones, the better our phones run in general. More devs should be as understanding as you!

**Comment by juvenalaraujo** [comment]
Working flawlessly now, thank you!

Em 23/08/2017 02:52, "Cormak" <notifications@github.com> escreveu:

@PaulWoitaschek <https://github.com/paulwoitaschek> Thank you for
understanding and changing the behavior of your app. The less unnecessary
running processes on our phones, the better our phones run in general. More
devs should be as understanding as you!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/issues/602#issuecomment-324198492>,
or mute the thread
