### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by m-ma** [PaulWoitaschek/MaterialAudiobookPlayer#603]
Actually I updated the project to the latest version with the exoplayer-flac library inside the path. Then I updated my development environment to the latest version of Android Studio and the latest version of the NDK. But when I try to sync with Gradle I run into a compile error "Gradle sync failed: GNUMAKE: Expected exactly one source file in compile step: com.android.build.gradle.external.gnumake.CommandClassifier$NativeCompilerBuildTool@6b5ccfab"

I work under Window 10 with Android Studio. Are there any preconditions, or what is going wrong?

Thanks in advance.

**Comment by PaulWoitaschek** [comment]
I can't say how this works on windows and I don't know how windows works.

I assume you need to either use a virtual machine or adjust all the commands accessing the shell in 
https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/tree/master/buildSrc/src/main/java/de/ph1b/audiobook/ndkGen

**Comment by Eifelschaf** [comment]
I have the same issue and I did not have it in the past. Perhaps it's linked to the ndk tools? I'll let you know if I find something.

**Comment by Eifelschaf** [comment]
@m-ma Go to the Android.mk in exoplayer-flac/src/main/jni and change the 

> '-DVERSION="1.3.1"'

 to

>  -DVERSION="1.3.1"

 (remove the single quotes) and it should work again. Not sure if this will work on unix, though. That should be tested by @PaulWoitaschek

**Comment by PaulWoitaschek** [comment]
Thanks! Let me know if this did not fix it for you.

**Comment by m-ma** [comment]
Thanks a lot. With -DVERSION=\"1.3.1\" it compiles like a charm. And after I fetched libopus into the path, today I was able to generate a new APK from the current sources. 

By the way, MaterialAudiobookPlayer is a very very great piece of software. I love it!

**Comment by PaulWoitaschek** [comment]
So the fetching of libopus did not work automatically on Windows?

**Comment by m-ma** [comment]
No, I had to manually fetch libopus into the path. And, of course, the same was for exoplayer-flac. I also copied manually the flac library sources into the patch.

I haven't thought about it, because it is described so in the READMEs of the libraries.

**Comment by PaulWoitaschek** [comment]
It would be great if you could investigate why the automatically fetching fails on windows.

The task should handle the downloading themselfes (so it builds on CI etc without manualy steps):

https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/master/buildSrc/src/main/java/de/ph1b/audiobook/ndkGen/PrepareOpus.kt#L35

https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/master/buildSrc/src/main/java/de/ph1b/audiobook/ndkGen/PrepareFlac.kt#L28

**Comment by PaulWoitaschek** [comment]
@Eifelschaf 
Maybe you can check if you can build the regular exoplayer extension: https://github.com/google/ExoPlayer/tree/release-v2/extensions/flac

And open the PR upstream with the `-DVERSION`? if it fails there too?

**Comment by Eifelschaf** [comment]
It fails because of the tar command. I have no idea how to solve that right
now.

Paul Woitaschek <notifications@github.com> schrieb am So., 11. Juni 2017,
10:52:

**Comment by DrOzturk** [comment]
"Perhaps we can add a note to the readme to build from Windows."
That would help... I am also having problems with building on Windows with Android Studio 3.0

**Comment by Eifelschaf** [comment]
Long story short: You'll have to download the two exo player libraries mentioned above. The rest should just work. (I'll create a pull request later)

**Comment by PaulWoitaschek** [comment]
Thanks!

**Comment by pjpeter29** [comment]
Hi all,

I'm having similar issues with running in Windows 10 with Android Studio.

I've attempting so first with Android Studio 3.5.3 which gave the error (after adding NDK and changing to Java 1.8): 
"org.gradle.internal.exceptions.LocationAwareException: This version of Android Studio cannot open this project, please retry with Android Studio 3.6 or newer."

While in Android Studio 3.6: "
The project is using an incompatible version of the Android Gradle plugin. 
To continue opening the project, the IDE will update the plugin to version 3.6.0-rc03."
- After which, it fails because it can't find the build.gradle file. 
- I also get output to the logs: "Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0."

Any suggestions are appreciated. I am able to open ExoPlayer-release-v2 without a problem so my system is not entirely broken, but I've been trying for two days and haven't been able to get Voice itself to build sucesssfully.

Thanks,
Peter
