### ISSUE TITLE
Various Issues Playing Walkaway

### ISSUE THREAD

**Issue by commonsguy** [PaulWoitaschek/MaterialAudiobookPlayer#610]
App-Version: 3.3.5
Phone Name: Nexus 5X
Android Version: 7.0.1

I am having a lot of trouble playing Cory Doctorow's "Walkaway" audiobook. Symptoms include:

- Playing the same section of the audiobook twice (e.g., a several-minute passage played once, then again an hour or so later, without my touching the controls, as if the app rewound under its own power)
- Refusing to start playing after pressing the play button
- Randomly skipping ahead in the file after trying to get the player to start playing by pressing play, then pause, then play

I don't know if it is due to the large files (the worst has been a single two-hour chapter) or something else. I have successfully played a couple of other audiobooks without issue, though those were on an older app version (before your recent wave of releases).

Note that my app edition is from F-Droid, if that matters. If you think that 3.3.6.2 might address the problems, let me know.

Also, if you have a tip jar somewhere, I'd be happy to send you $20 so you can purchase a copy of "Walkaway" to see if you can reproduce the problems.

**Comment by PaulWoitaschek** [comment]
I'm pretty sure this is either because of issues with the file itself or a bug in [ExoPlayer](https://github.com/google/ExoPlayer).
All I could do is report a bug there, so it might make sense if you did that directly. They also have a gmail address where you can send stuff with unclear license.

> (before your recent wave of releases).

FDroid could not build stuff containing the ConstraintLayout for like a year. So the wave was more like a continuous flow of water. Just coming at once for fdroid users.
